{{-- Load Navigation, these are autogenerated with links in ACP\Logical\Menu Class from each Module --}}
<x-acp::navigation>

    {{-- Create Menu --}}
    @foreach( \Modules\ACP\Services\MenuService::getItems() as $menu)
        <x-acp::navigation.items href="{{ ($menu['isRoute']) ? route($menu['link']) : $menu['link'] }}">
            {{$menu['name']}}
        </x-acp::navigation.items>
    @endforeach
    {{-- /Create Menu --}}

    {{-- Logout Button --}}
    <form method="POST" action="{{ route('logout') }}">
        @csrf
        <x-acp::navigation.items href="{{ route('logout') }}" onclick="event.preventDefault(); this.closest('form').submit();">
            <i class="fa-solid fa-arrow-right-from-bracket text-main_brand"></i>
        </x-acp::navigation.items>
    </form>
    {{-- /Logout Button --}}

</x-acp::navigation>


